import { Product, User } from '../store/appStore';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Gaurav Paul',
    email: 'gaurav@epium.com',
    role: 'user',
    isGuest: false,
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400',
  },
  {
    id: 'admin',
    name: 'Admin Master',
    email: 'admin@epium.com',
    role: 'admin',
    isGuest: false,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
  }
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'Imperial Banarasi Silk',
    artisan: 'Master Weaver Kabir',
    artisanId: 'a1',
    location: 'Varanasi',
    state: 'Uttar Pradesh',
    category: 'women',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800', 
      'https://images.unsplash.com/photo-1583394838336-acd977730f90?w=800',
    ],
    price: 45000,
    originalPrice: 52000,
    story: 'Kabir comes from a line of royal weavers. This piece took 3 months to complete, using 24-carat gold threads.',
    details: 'Pure Katan Silk with intricate Zari work. Standard length 5.5m.',
    material: 'Katan Silk',
    sizes: ['Standard'],
    tags: ['luxury', 'wedding', 'silk'],
    inStock: true,
    rating: 4.9,
    reviewCount: 124,
    artisanIncentive: 82,
  },
  {
    id: 'p2',
    title: 'Heritage Cashmere Gown',
    artisan: 'Zoya Khan',
    artisanId: 'a2',
    location: 'Srinagar',
    state: 'Kashmir',
    category: 'women',
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800', // Luxury dress
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
    ],
    price: 38500,
    story: 'Zoya uses a unique triple-ply cashmere technique, making this gown feel like a second skin.',
    details: '100% Himalayan Cashmere. Hand-tailored seams.',
    material: 'Cashmere',
    tags: ['luxury', 'evening', 'exclusive'],
    inStock: true,
    rating: 5.0,
    reviewCount: 38,
    artisanIncentive: 85,
  },
  {
    id: 'p3',
    title: 'Royal Indigo Sherwani',
    artisan: 'Rahim Ali',
    artisanId: 'a3',
    location: 'Lucknow',
    state: 'Uttar Pradesh',
    category: 'men',
    images: [
      'https://images.unsplash.com/photo-1598124837775-7c74024b81ce?w=800', // High-end Men's ethnic
      'https://images.unsplash.com/photo-1597983073493-80f2dff7efba?w=800',
    ],
    price: 22000,
    story: 'Traditional Chikankari embroidery reimagined for the modern king.',
    details: 'Pure Linen with Silk Hand-embroidery.',
    material: 'Linen',
    tags: ['men', 'wedding', 'ethnic'],
    inStock: true,
    rating: 4.8,
    reviewCount: 64,
    artisanIncentive: 78,
  },
  {
    id: 'p4',
    title: 'Marble Inlay Sculpture',
    artisan: 'Mansoor Qureshi',
    artisanId: 'a4',
    location: 'Agra',
    state: 'Uttar Pradesh',
    category: 'home-decor',
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800', 
      'https://images.unsplash.com/photo-1590424740073-1f190ca38515?w=800',
    ],
    price: 15800,
    story: 'Pietra Dura technique used in the Taj Mahal. Semi-precious stones inlaid in white Makrana marble.',
    details: 'Makrana Marble. Lapis Lazuli and Malachite inlays.',
    material: 'Marble',
    tags: ['interior', 'heritage', 'agrastyle'],
    inStock: true,
    rating: 4.9,
    reviewCount: 42,
    artisanIncentive: 80,
  },
  {
    id: 'p5',
    title: 'Gilded Lotus Mirror',
    artisan: 'Sanjay Soni',
    artisanId: 'a5',
    location: 'Jaipur',
    state: 'Rajasthan',
    category: 'home-decor',
    images: [
      'https://images.unsplash.com/photo-1616489953149-8e411b03378b?w=800', // Luxury mirror
      'https://images.unsplash.com/photo-1520006403909-838d6b92c22e?w=800',
    ],
    price: 12400,
    story: 'Repoussé silver work on wood. Sanjay replicates the ripples of a sacred pond.',
    details: 'Silver-plated Wood. Anti-tarnish coating.',
    material: 'Teak/Silver',
    tags: ['home', 'luxury', 'spiritual'],
    inStock: true,
    rating: 4.7,
    reviewCount: 56,
    artisanIncentive: 72,
  },
  {
    id: 'p6',
    title: 'Midnight Pashmina',
    artisan: 'Farooq Ahmed',
    artisanId: 'a6',
    location: 'Kashmir',
    state: 'Kashmir',
    category: 'women',
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
      'https://images.unsplash.com/photo-1520006403909-838d6b92c22e?w=800',
    ],
    price: 32000,
    story: 'Hand-combed and hand-spun. The true soft gold of the Himalayas.',
    details: 'Pure Grade A Pashmina.',
    material: 'Wool',
    tags: ['winter', 'women', 'luxury'],
    inStock: true,
    rating: 5.0,
    reviewCount: 92,
    artisanIncentive: 88,
  },
  {
    id: 'p7',
    title: 'Heritage Suede Jacket',
    artisan: 'Amir Khan',
    artisanId: 'a7',
    location: 'Jodhpur',
    state: 'Rajasthan',
    category: 'Jackets',
    images: [
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800',
      'https://images.unsplash.com/photo-1591047139829-d91aec36beea?w=800',
    ],
    price: 18500,
    story: 'Hand-dyed suede stitched with traditional Rajasthani leather techniques.',
    details: 'Genuine Suede Leather. Silk Lining.',
    material: 'Suede',
    tags: ['luxury', 'men', 'autumn'],
    inStock: true,
    rating: 4.8,
    reviewCount: 45,
    artisanIncentive: 82,
  },
  {
    id: 'p8',
    title: 'Organic Cotton Tee',
    artisan: 'Lata Devi',
    artisanId: 'a8',
    location: 'Coimbatore',
    state: 'Tamil Nadu',
    category: 'T-Shirts',
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800',
    ],
    price: 3200,
    story: 'Ethically sourced organic cotton, hand-spun in the heart of the cotton belt.',
    details: '100% Organic Cotton. Naturally dyed.',
    material: 'Cotton',
    tags: ['casual', 'sustainable'],
    inStock: true,
    rating: 4.9,
    reviewCount: 230,
    artisanIncentive: 75,
  },
  {
    id: 'p9',
    title: 'Linen Master Pants',
    artisan: 'Vikram Singh',
    artisanId: 'a9',
    location: 'Kerala',
    state: 'Kerala',
    category: 'Pants',
    images: [
      'https://images.unsplash.com/photo-1594932224010-7566d6771d41?w=800',
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
    ],
    price: 6400,
    story: 'Meticulously tailored linen trousers designed for breathable luxury.',
    details: 'Premium Handloom Linen.',
    material: 'Linen',
    tags: ['men', 'summer', 'ethic'],
    inStock: true,
    rating: 4.7,
    reviewCount: 88,
    artisanIncentive: 80,
  },
  {
    id: 'p10',
    title: 'Bomber Heritage Jacket',
    artisan: 'Sanjay Soni',
    artisanId: 'a5',
    location: 'Jaipur',
    state: 'Rajasthan',
    category: 'Jackets',
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aec36beea?w=800',
      'https://images.unsplash.com/photo-1621600411666-474d8935a60a?w=800',
    ],
    price: 24000,
    story: 'Merging classic bomber silhouette with royal Jaipur embroidery.',
    details: 'Wool Blend with Silk embroidery.',
    material: 'Wool/Silk',
    tags: ['luxury', 'exclusive'],
    inStock: true,
    rating: 5.0,
    reviewCount: 12,
    artisanIncentive: 90,
  },
  {
    id: 'p11',
    title: 'Artisan Fit Chinos',
    artisan: 'Rahim Ali',
    artisanId: 'a3',
    location: 'Lucknow',
    state: 'Uttar Pradesh',
    category: 'Pants',
    images: [
      'https://images.unsplash.com/photo-1473966968600-fa804b86827b?w=800',
      'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800',
    ],
    price: 5200,
    story: 'Twice-dyed cotton chinos with a modern artisan fit.',
    details: 'Heavyweight Brushed Cotton.',
    material: 'Cotton',
    tags: ['men', 'casual', 'essential'],
    inStock: true,
    rating: 4.6,
    reviewCount: 145,
    artisanIncentive: 70,
  },
  {
    id: 'p12',
    title: 'Royal Knit Tee',
    artisan: 'Zoya Khan',
    artisanId: 'a2',
    location: 'Kashmir',
    state: 'Kashmir',
    category: 'T-Shirts',
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800',
    ],
    price: 8900,
    story: 'Fine-knit luxury tee with a silk-touch finish.',
    details: 'Mercerized Cotton with Silk infusion.',
    material: 'Mercerized Cotton',
    tags: ['luxury', 'essential', 'men'],
    inStock: true,
    rating: 5.0,
    reviewCount: 56,
    artisanIncentive: 85,
  },
  {
    id: 'p13',
    title: 'Emerald Zardosi Saree',
    artisan: 'Priya Das',
    artisanId: 'a10',
    location: 'Varanasi',
    state: 'Uttar Pradesh',
    category: 'Saree',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1200',
      'https://images.unsplash.com/photo-1583394838336-acd977730f90?w=1200',
    ],
    price: 52000,
    story: 'An emerald masterpiece featuring intricate Zardosi work that takes over 200 hours of hand labor.',
    details: 'Pure Banarasi Silk. Real Gold thread.',
    material: 'Silk',
    tags: ['heritage', 'wedding', 'luxury'],
    inStock: true,
    rating: 4.9,
    reviewCount: 15,
    artisanIncentive: 85,
  },
  {
    id: 'p14',
    title: 'Heritage Cashmere Coat',
    artisan: 'Farooq Ahmed',
    artisanId: 'a6',
    location: 'Srinagar',
    state: 'Kashmir',
    category: 'Coat',
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=1200',
      'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=1200',
    ],
    price: 48000,
    story: 'The ultimate shield against cold, crafted from the finest hand-woven cashmere in Kashmir.',
    details: '100% Grade A Cashmere. Silk lining.',
    material: 'Cashmere',
    tags: ['winter', 'luxury', 'exclusive'],
    inStock: true,
    rating: 5.0,
    reviewCount: 8,
    artisanIncentive: 90,
  },
  {
    id: 'p15',
    title: 'Midnight Velvet Saree',
    artisan: 'Kabir W.',
    artisanId: 'a1',
    location: 'Varanasi',
    state: 'Uttar Pradesh',
    category: 'Saree',
    images: [
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=1200',
      'https://images.unsplash.com/photo-1610030375424-5f118ed5287f?w=1200',
    ],
    price: 36000,
    story: 'A dark, moody velvet saree designed for high-end evening events.',
    details: 'Italian Velvet. Hand-embellished border.',
    material: 'Velvet',
    tags: ['evening', 'modern', 'luxury'],
    inStock: true,
    rating: 4.8,
    reviewCount: 22,
    artisanIncentive: 80,
  }
];

export const MOCK_ARTISANS = [
  { id: '1', name: 'Kabir W.', craft: 'Silk Weaving', image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300' },
  { id: '2', name: 'Zoya K.', craft: 'Cashmere Tailoring', image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300' },
  { id: '3', name: 'Rahim A.', craft: 'Chikankari', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300' },
  { id: '4', name: 'Mansoor Q.', craft: 'Stone Inlay', image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300' },
  { id: 'a7', name: 'Amir Khan', craft: 'Leather Artisanship', image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300' },
  { id: 'a8', name: 'Lata Devi', craft: 'Handloom Cotton', image: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=300' },
  { id: 'a9', name: 'Vikram Singh', craft: 'Master Tailoring', image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300' },
];
